name: Automated Test via Selenium

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Execute test via github actions
      run: mvn clean test -DtestSuite=Regression.xml -Dbrowser=ChromeHeadless -Durl=https://opensource-demo.orangehrmlive.com
